name: Get Release
description: Get a release by tag, latest or current release
author: Giao Ho
inputs:
  tag_name:
    description: Specify tag instead of using checkout tag.
    required: false

  latest:
    description: Should get latest release?
    required: false
    default: 'false'
  prerelease:
    # This input will be ignored if `latest = false`
    description: Find the latest release including the pre-releases
    required: false
  pattern:
    description: A pattern string to filter the releases by tag_name
    required: false

  debug:
    description: Show ouputs
    required: false
  throwing:
    description: Fail when no release was found
    required: false
outputs:
  id:
    description: The ID of the Release
  node_id:
    description: The node ID
  url:
    description: The release url
  html_url:
    description: The url users can navigate to in order to view the release
  assets_url:
    description: The release assets url
  upload_url:
    description: The url for uploading assets to the release
  name:
    description: The release name
  tag_name:
    description: The tag name
  body:
    description: The release body
  draft:
    description: Is draft
  prerelease:
    description: Is pre-release
  target_commitish:
    description: The branch name
  created_at:
    description: Created date
  published_at:
    description: Published date
runs:
  using: node12
  main: action/index.js
branding:
  icon: tag
  color: blue
