# This is a basic workflow to help you get started with Actions

name: Release Testing

# Controls when the action will run.
on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current release
        uses: ./
        with:
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest release
        uses: ./
        with:
          latest: true
          pattern: v.*
          prerelease: true
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
